version: '3'

services:
  mysql:
    container_name: mysql
    build: .
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sf1
      #volumes:
      #- "./setup_db.sh:/docker-entrypoint-initdb.d"
    ports:
      - 3306:3306
      
